geolite:
  baggage: visitor_info
  db:
    asn: geolite/GeoLite2-ASN.mmdb
    city: geolite/GeoLite2-City.mmdb
    country: geolite/GeoLite2-Country.mmdb
  exclude:
    - asn.ipAddress
    - asn.hostAddress
    - asn.prefixLength
  maxTrustedIndex: 1
logging:
  level:
    io.github.hamza.geolite: DEBUG
management:
  tracing:
    baggage:
      correlation:
        fields:
          - ${geolite.baggage}
      remote-fields:
        - ${geolite.baggage}
