geolite:
  db:
    asn: geolite/GeoLite2-ASN.mmdb
    city: geolite/GeoLite2-City.mmdb
    country: geolite/GeoLite2-Country.mmdb
  baggage: visitor_info
  maxTrustedIndex: 1
management:
  tracing:
    baggage:
      correlation:
        fields:
          - ${geolite.baggage}
      remote-fields:
        - ${geolite.baggage}
